telegram:
  token: 7712232269:AAFOAIIMx8_CP-KrGIWk8fA8pLdDwlKooCc

database:
  host: "db"
  port: 5432
  user: "postgres"
  password: "349349"
  database: "EmotionalCompass"
  sslmode: "disable"

bot:
  state_files:
    - "./app/config/states/color_zone.json"
    - "./app/config/states/diaries.json"
    - "./app/config/states/emotion_body_reactions.json"
    - "./app/config/states/emotion_body_techniques.json"
    - "./app/config/states/emotion_features.json"
    - "./app/config/states/emotion_meditations.json"
    - "./app/config/states/emotion_shades.json"
    - "./app/config/states/emotional_cognitive_techniques.json"
    - "./app/config/states/emotional_self_help.json"
    - "./app/config/states/emotions.json"
    - "./app/config/states/emotions_limited.json"
    - "./app/config/states/focus.json"
    - "./app/config/states/meditations.json"
    - "./app/config/states/payments.json"
    - "./app/config/states/start.json"
    - "./app/config/states/state.json"