telegram:
  token: 7712232269:AAFOAIIMx8_CP-KrGIWk8fA8pLdDwlKooCc

database:
  host: "db"
  port: 5432
  user: "postgres"
  password: "349349"
  database: "EmotionalCompass"
  sslmode: "disable"

bot:
  state_files:
    - "${STATE_FILES_PATH}/color_zone.json"
    - "${STATE_FILES_PATH}/diaries.json"
    - "${STATE_FILES_PATH}/emotion_body_reactions.json"
    - "${STATE_FILES_PATH}/emotion_body_techniques.json"
    - "${STATE_FILES_PATH}/emotion_features.json"
    - "${STATE_FILES_PATH}/emotion_meditations.json"
    - "${STATE_FILES_PATH}/emotion_shades.json"
    - "${STATE_FILES_PATH}/emotional_cognitive_techniques.json"
    - "${STATE_FILES_PATH}/emotional_self_help.json"
    - "${STATE_FILES_PATH}/emotions.json"
    - "${STATE_FILES_PATH}/emotions_limited.json"
    - "${STATE_FILES_PATH}/focus.json"
    - "${STATE_FILES_PATH}/meditations.json"
    - "${STATE_FILES_PATH}/payments.json"
    - "${STATE_FILES_PATH}/start.json"
    - "${STATE_FILES_PATH}/state.json"